

####--------------------------------------------USERS-------------
###-----------------------------/get user
GET http://localhost:3000/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTY1ODg0MjkzMSwiZXhwIjoxNjU4ODQ2NTMxfQ.id4xQfkHWIC7S0z3yw1h7imA9hOdsvs4ID0JoYE0RUg


###----------------------------/register

POST http://localhost:3000/api/register
Content-Type: application/json

 {
    "full_name": "marius1",
    "email": "marius1@xxx.lt",
    "password": "123456"
    
  }

###------------------------------/login

POST http://localhost:3000/api/login
Content-Type: application/json

 {
    "full_name": "marius1",
    "email": "marius1@xxx.lt",
    "password": "123456"
    
  }
###-------------------------------------------------------------QUESTION--------------
###---------------------------------------GET ALL questions
GET http://localhost:3000/api/questions 

###--------------------------------------POST question
POST http://localhost:3000/api/questions 
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NTg5MDcyODEsImV4cCI6MTY1ODkxMDg4MX0.BKtKLColXxbyyRNbuDIH-JzMQCeofuDUvD4HePhSouo

{
"title_q": "Medzioklinis suo2", 
"body_q": "Koki suni pirkti2?",
"user_id": 2
}

###-----------------------------------UPDATE question

PATCH http://localhost:3000/api/questions/1
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NTg5MDk2MTgsImV4cCI6MTY1ODkxMzIxOH0.joSpgfN5us-WYhK2vKbU8yv9kfd59ID288eI8DVR3f8

{
"title_q": "Medzioklinis suo23",
"body_q": "Kokio suns nepirkti!!!!!???333444"

}

###-----------------------------------DELETE

DELETE http://localhost:3000/api/questions/5
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NTg5MDcyODEsImV4cCI6MTY1ODkxMDg4MX0.BKtKLColXxbyyRNbuDIH-JzMQCeofuDUvD4HePhSouo

###----------------------------------------ANSWERS----------
###---------------------------------------------------------------------
###----------------------------Get answers by question ID
GET http://localhost:3000/api/questions/1/answers

###---------------------------Post answers by question ID

POST http://localhost:3000/api/questions/1/answers
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NTg5MTAxNjIsImV4cCI6MTY1ODkxMzc2Mn0.LyE2gSoDhyhCwfF5DdFp6RTDUwcPx5Le8xN7ahwyJz8

{

"body_a": "Nepirk suns!",
"user_id": 2
}

###-----------------------------------UPDATE answer

PATCH http://localhost:3000/api/answers/1
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NTg5MDk2MTgsImV4cCI6MTY1ODkxMzIxOH0.joSpgfN5us-WYhK2vKbU8yv9kfd59ID288eI8DVR3f8

{

"body_a": "Geriau pirkti kudlota suni Patch"

}
###-----------------------------------DELETE answer

DELETE http://localhost:3000/api/answers/3
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NTg5MDk2MTgsImV4cCI6MTY1ODkxMzIxOH0.joSpgfN5us-WYhK2vKbU8yv9kfd59ID288eI8DVR3f8

###-------------------------------------LIKE question

PATCH http://localhost:3000/api/questions/likes
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NTg5MDk2MTgsImV4cCI6MTY1ODkxMzIxOH0.joSpgfN5us-WYhK2vKbU8yv9kfd59ID288eI8DVR3f8

{

"id_q": 1

}
###-------------------------------------DISLIKE question

PATCH http://localhost:3000/api/questions/dislikes
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NTg5MDk2MTgsImV4cCI6MTY1ODkxMzIxOH0.joSpgfN5us-WYhK2vKbU8yv9kfd59ID288eI8DVR3f8

{

"id_q": 1

}