


###-----------------------------/get user
GET http://localhost:3000/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTY1ODg0MjkzMSwiZXhwIjoxNjU4ODQ2NTMxfQ.id4xQfkHWIC7S0z3yw1h7imA9hOdsvs4ID0JoYE0RUg


###----------------------------/register

POST http://localhost:3000/api/register
Content-Type: application/json

 {
    "full_name": "marius1",
    "email": "marius1@xxx.lt",
    "password": "123456"
    
  }

###------------------------------/login

POST http://localhost:3000/api/login
Content-Type: application/json

 {
    "full_name": "marius1",
    "email": "marius1@xxx.lt",
    "password": "123456"
    
  }
###---------------------------------------GET questions
GET http://localhost:3000/api/questions 

###--------------------------------------POST question
POST http://localhost:3000/api/questions 
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NTg4NjczNTMsImV4cCI6MTY1ODg3MDk1M30.wEfaDfxnwk2G0OKYt4kZ61glV0srYJg4D5HhePoSn-M

{
"title_q": "Medzioklinis suo", 
"body_q": "Koki suni pirkti?",
"user_id": 2
}

###-----------------------------------

PATCH http://localhost:3000/api/questions/3
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NTg4NjczNTMsImV4cCI6MTY1ODg3MDk1M30.wEfaDfxnwk2G0OKYt4kZ61glV0srYJg4D5HhePoSn-M

{
"body_q": "Kokio suns nepirkti!!!!!"
}